Repository Unknown-Project-Here/project-z, pull requests merged in 2025-02, with the labels that each got.

#8 Roles and permissions functionality
  app/Enums/ProjectPermission.php
  app/Enums/ProjectRole.php
  app/Http/Controllers/ProjectController.php
  app/Http/Requests/ProjectRenameRequest.php
  app/Models/Project.php
  app/Models/ProjectUser.php
  app/Models/User.php
  app/Policies/ProjectPolicy.php
  database/factories/ProjectFactory.php
  database/migrations/2025_02_07_065600_create_project_user_table.php
  database/seeders/DatabaseSeeder.php
  phpunit.xml
  routes/web.php
  tests/Feature/ProjectDeleteTest.php
  tests/Feature/ProjectRenameTest.php
Labels: enhancement, backend

#10 Add Project Creation and Edit Flow
  app/Http/Controllers/ProjectController.php
  resources/js/Components/icons.tsx
  resources/js/Components/ui/textarea.tsx
  resources/js/Pages/Project/Create.tsx
  resources/js/Pages/Project/Edit.tsx
  resources/js/Pages/Project/Index.tsx
  resources/js/Pages/Project/Partials/ProjectDetails.tsx
  resources/js/Pages/Project/Partials/ProjectSteps.tsx
  resources/js/Pages/Project/Show.tsx
  resources/js/lib/utils.ts
  resources/js/types/index.d.ts
  routes/web.php
Labels: backend, frontend

#23 refactor: Enhance Project model and display with detailed stack and c…
  app/Http/Controllers/ProjectController.php
  app/Models/Option.php
  app/Models/Project.php
  app/Models/User.php
  package-lock.json
  package.json
  resources/js/Pages/Project/Show.tsx
  resources/js/types/index.d.ts
Labels: bug, backend, frontend

#24 feat: Add ProjectInvitation model and migration for project member in…
  app/Models/Project.php
  app/Models/ProjectInvitation.php
  database/migrations/2025_02_13_090911_create_project_invitations_table.php
Labels: enhancement, backend

#29 Updated Project Components
  app/Http/Controllers/ProjectController.php
  database/factories/ProjectFactory.php
  public/icons/discord.svg
  resources/js/Components/projects/index/ContactItem.tsx
  resources/js/Components/projects/index/ContactLinks.tsx
  resources/js/Components/projects/index/ProjectCard.tsx
  resources/js/Components/projects/index/ProjectStack.tsx
  resources/js/Components/ui/badge.tsx
  resources/js/Pages/Dashboard.tsx
  resources/js/Pages/Project/Index.tsx
  resources/js/Pages/Project/Show.tsx
  resources/js/types/index.d.ts
Labels: enhancement
